name: ZEngine Cmake Linux Workflow

on:
  workflow_call:

env:
  CMAKE_INSTALL_PREFIX: "${{github.workspace}}/linux_install"

jobs:
  Linux-Build:
    name: cmake-build-linux
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update the list of packages
        run: sudo apt-get update

      - name: Install Dependencies
        run: sudo apt-get install cmake software-properties-common gcc g++ libx11-xcb-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libasound2-dev libgl1-mesa-dev libpulse-dev libdbus-1-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxss-dev libxt-dev libxxf86vm-dev libxkbcommon-dev

      - name: CMake Configure
        run: cmake -B builds 

      - name: CMake Build
        run: cmake --build builds 

      - name: CMake Install
        run: mkdir install && cmake --install builds --prefix linux_install

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-linux
          if-no-files-found: error
          path: linux_install
