# CMake Dependency build of ZEngine for macOS
#
name: ZEngine macOS Workflow

on:
  workflow_call:

jobs:
  cmake-build:
    name: cmake-build-macOS-${{ matrix.architecture }}
    runs-on: ${{ matrix.architecture == 'x64' && 'macos-15-intel' || 'macos-latest' }}
    strategy:
      matrix:
        architecture: ['x64', 'arm64']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: CMake Configure
        run: cmake -B builds_${{matrix.architecture}} -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF -DASSIMP_WARNINGS_AS_ERRORS=OFF -DSPIRV_WERROR=OFF -DFMT_INSTALL=ON -DSPDLOG_INSTALL=ON -DENTT_INSTALL=ON

      - name: CMake Build
        run: cmake --build builds_${{matrix.architecture}} --parallel

      - name: CMake Install
        run: mkdir install_${{matrix.architecture}} && cmake --install builds-${{matrix.architecture}} --prefix install_${{matrix.architecture}}  

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-macOS-${{ matrix.architecture }}
          if-no-files-found: error
          path: install_${{matrix.architecture}}
