# CMake Dependency build of ZEngine for macOS
#
name: ZEngine macOS Workflow

on:
  workflow_call:

jobs:
  cmake-build:
    name: cmake-build-macOS-${{ matrix.architecture }}
    runs-on: ${{ matrix.architecture == 'x64' && 'macos-15-intel' || 'macos-latest' }}
    strategy:
      matrix:
        architecture: ['x64', 'arm64']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: CMake Configure
        run: cmake -G Ninja -B builds_${{matrix.architecture}} -DCMAKE_INSTALL_PREFIX=install_${{matrix.architecture}} -DCMAKE_CONFIGURATION_TYPES="Release" -DENTT_INSTALL=ON -DFMT_INSTALL=ON -DGLSLANG_ENABLE_INSTALL=ON -DINSTALL_PROJECT=ON -DJSON_Install=ON -DSPDLOG_INSTALL=ON -DSPIRV_HEADERS_ENABLE_INSTALL=ON -DUUID_ENABLE_INSTALL=ON -DVMA_ENABLE_INSTALL=ON -DVULKAN_HEADERS_ENABLE_INSTALL=ON -DYAML_CPP_INSTALL=ON -DCLI11_SINGLE_FILE=ON -DCLI11_FULL_INSTALL=ON -DBUILD_SHARED_LIBS=ON

      - name: CMake Build
        run: cmake --build builds_${{matrix.architecture}} 

      - name: CMake Install
        run: mkdir install_${{matrix.architecture}} && cmake --install builds_${{matrix.architecture}} --prefix install_${{matrix.architecture}}

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-macOS-${{ matrix.architecture }}
          if-no-files-found: error
          path: install_${{matrix.architecture}}
