# CMake Dependency Build of ZEngine for Windows
#
name: Windows Build Workflow

env:
  CMAKE_INSTALL_PREFIX: "${{github.workspace}}/install"

on:
  workflow_call:

jobs:
  cmake-build:
    name: cmake-build-windows
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: CMake Configure
        run: cmake -B builds -DENTT_INSTALL=ON -DFMT_INSTALL=ON -DGLSLANG_ENABLE_INSTALL=ON -DINSTALL_PROJECT=ON -DJSON_Install=ON -DSPDLOG_INSTALL=ON -DSPIRV_HEADERS_ENABLE_INSTALL=ON -DUUID_ENABLE_INSTALL=ON -DVMA_ENABLE_INSTALL=ON -DVULKAN_HEADERS_ENABLE_INSTALL=ON -DYAML_CPP_INSTALL=ON -DCLI11_SINGLE_FILE=ON -DCLI11_FULL_INSTALL=ON -DBUILD_SHARED_LIBS=ON
        shell: pwsh

      - name: CMake Build
        run: cmake --build builds --parallel --config Release
        shell: pwsh

      - name: CMake Install
        run: mkdir install && cmake --install builds --prefix install --config Release
        shell: pwsh

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-Windows
          if-no-files-found: error
          path: install
