# CMake Dependency Build of ZEngine for Windows
#
name: Windows Build Workflow

env:
  CMAKE_INSTALL_PREFIX: "${{github.workspace}}/install"

on:
  workflow_call:

jobs:
  cmake-build:
    name: cmake-build-windows
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: CMake Configure
        run: cmake -B builds
        shell: pwsh

      - name: CMake Build
        run: cmake --build builds --parallel --config Release
        shell: pwsh

      - name: CMake Install
        run: mkdir install && cmake --install builds --prefix install --config Release
        shell: pwsh

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-Windows
          if-no-files-found: error
          path: install
